web:
  build: ./web
  working_dir: /opt/build
  volumes_from:
    - gulp
  links:
    - api:api
  ports:
    - 8080:80 # for nginx

gulp:
  build: ./web
  command: /opt/build/node_modules/.bin/gulp watch
  working_dir: /opt/build
  volumes:
    - ./web/src:/opt/src
    - /opt/www
    - /opt/build
  ports:
    - 8181:3000 # for gulp watch

api:
  build: ./api
  command: rerun github.com/shorrockin/clikr
  volumes:
    - ./api/src:/gopath/src/github.com/shorrockin/clikr
  ports:
    - 3000:3000

# go convey tests commented out, not quite working - scans everything
# and eventually crashes. this can't be how it's expected to work?
test:
  build: ./test
  volumes:
    - ./api/src:/gopath/src/github.com/shorrockin/clikr
  ports:
    - 9090:3000
